package:
  name: base
  description: |
    Contains templates for the various builtin elements for HTML, Markdown, and LaTeX formats. This package forms the
    base of most courses projects, hence its name.
    

  version: 0.1
  authors:
    - Anton Mølbjerg Eskildsen
