package:
  name: theme_default
  description: The default theme (uses Tailwind CSS). Provides layouts for HTML.
  version: 0.1.0
  authors:
    - Anton Mølbjerg Eskildsen

dependencies:
  base:
    version: 0.1
    file: ../base

layouts:
  section:
    html: templates/layouts/section.tera.html
  nav:
    html: templates/layouts/nav.tera.html
  index:
    html: templates/layouts/index.tera.html
  bar:
    html: templates/layouts/bar.tera.html