[package]
name = "cdoc-parser"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"


[dependencies]
pest = "2.7.3"
pest_derive = "2.7.3"

[dev-dependencies]
pest-test = "0.1.5"
pest-test-gen = "0.1.6"
lazy_static = "1.4.0"