url_prefix: /courses

custom:
  crates:
    cdoc: https://crates.io/crates/cdoc
    courses: https://crates.io/crates/courses

preprocessors:
  - name: exercises

settings:
  solutions: false

repository:
  url: "https://github.com/antonmeskildsen/courses/"

outputs:
  - html: {}

notebook_meta:
  kernelspec:
    display_name: Python
    language: python3
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: py
    mimetype: text/x-python
    name: python