url_prefix = "/courses"
katex_output= true

[custom.crates]
cdoc = "https://crates.io/crates/cdoc"
courses = "https://crates.io/crates/courses"

[[outputs]]
html = {}

[[preprocessors]]
name="exercises"


[notebook_meta]
kernelspec = { display_name = "Python", language = "python3", name = "python3" }
[notebook_meta.language_info]
codemirror_mode = { name = "ipython", version = 3 }
file_extension = "py"
mimetype = "text/x-python"
name = "python"
