
courses:
  version: ^0.9

url_prefix: /courses

plugins:
  base:
    version: 0.1
    features:
      - html
      - shortcodes
  theme_default:
    version: 0.1
    features:
      - html
      - shortcodes
  nb_format:
    version: 0.1
    features:
      - html
      - shortcodes

custom:
  crates:
    cdoc: https://crates.io/crates/cdoc
    courses: https://crates.io/crates/courses

repository:
  url: "https://github.com/coursesproject/courses"

packages:
  - name: coursesproject/base
    version: 0.1
    features:
      - html

profiles:
  draft:
    mode: draft
    parser: # Parser settings
      preprocessors:
        - md_labels:
      solutions: false # Don't include exercise solutions
    render_extensions:
      html:
        - cells:
        - doc_structure:
            max_heading_level: 3
            included_commands:
              - task
    formats:
      - html: {}
      - dynamic:
          name: ast
          extension: json
          template_prefix: html
          renderer:
            json:
  release:
    mode: release
    parser: # Parser settings
      preprocessors:
        - md_labels:
      solutions: false # Don't include exercise solutions
    render_extensions:
      html:
        - cells:
        - doc_structure:
            max_heading_level: 3
            included_commands:
              - task
    formats:
      - html: { }


notebook_meta:
  kernelspec:
    display_name: Python
    language: python3
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: py
    mimetype: text/x-python
    name: python