url_prefix: /courses
katex_output: true

custom:
  crates:
    cdoc: https://crates.io/crates/cdoc
    courses: https://crates.io/crates/courses

repository:
  url: https://github.com/antonmeskildsen/courses/tree/main/docs

outputs:
  - html
  - latex

parsers:
  html:
    settings:
      solutions: false
      notebook_outputs: true
    md_processors:
      - type: shortcodes
      - type: katex
    ast_processors:
      - type: exercises
  latex:
    settings:
      solutions: false
      notebook_outputs: true
    md_processors:
      - type: shortcodes
      - type: katex
    ast_processors:
      - type: exercises