name: courses-docs

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mirlahiji/rust-action@master
      - run: |
          cargo install --path ./
          cd docs
          courses build
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target-branch: gh-pages
          build_dir: docs/build/release/html/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
